version: '3.8'

services:
  app:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    volumes:
      - ./logs:/logs

  redis:
    image: redis:6.2.6
    volumes:
      - redis-data:/data

volumes:
  redis-data:
