# fly.toml file generated for sqa-label-studio on 2023-04-17T21:33:29+03:00

app = "sqa-label-studio"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"
processes = []

[env]
  LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
  LABEL_STUDIO_HOST="sqa-label-studio.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  autostart = true
  autostop = false
  http_checks = []
  internal_port = 9090
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
  source="app_data"
  destination="/label-studio/data"
