name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest

  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install poetry

      - name: Install dependencies
        run: poetry install

      - name: Train model
        run: >-
          poetry run python labeler/cli/main.py train
          --labels tests/fixtures/doctype/labels.csv
          --logs ./tests/fixtures/doctype
          --save tests/fixtures/doctype.model
