name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install poetry

      - run: poetry install
      - run: poetry run black --diff --check .
      - run: poetry run flake8
      - run: poetry run pytest
      - run: >-
          poetry run python labeler/cli/main.py train
          --labels tests/fixtures/doctype/labels.csv
          --logs ./tests/fixtures/doctype
          --save tests/fixtures/doctype.model
